### PR TITLE
Fixed Bring and added other capabilities

### PR DESCRIPTION
**Pull request by Berkeratay**
Fixed: Bring, English Locale
Add: Bring Back, Teleport Back, Freeze, Unfreeze, Kill, Turkish Locale
Missing: Other Language Updates

### CODE REVIEW

**Comment by Berkeratay** [comment]
@Korioz code might not at be at it's best but solved the problem for our server.
I know you suggested config layout for the submenu but i will be happy if you guide me to further organized the admin menu, since suggested workaround did not work for me.

**Comment by Korioz** [comment]
Do you know how git versioning work ? like wtf you juste uploaded a new file who is from an outdated version

**Comment by Berkeratay** [comment]
I will check the latest version of the code i am sorry.

**Comment by Berkeratay** [comment]
Upon checking files i see there are some changes i did not even make i will take a look at that.

**Pull request closed without merging**
