### PR TITLE
Fixed Money for latest ESX

### PR DESCRIPTION
**Pull request by MonsterZockerHD**
yeah it really works

### CODE REVIEW

**Comment by ArnaudSmith62** [comment]
Hi , i can't see the money...

**Comment by Korioz** [comment]
Waiting for esx to stop doing breaking commits and after that i will update

**Comment by MonsterZockerHD** [comment]
> 
> Hi , i can't see the money...

Maybe you don't have latest es_extended

**Comment by MonsterZockerHD** [comment]
> Waiting for esx to stop doing breaking commits and after that i will update

**since esx 2.0 is out idk if this works anymore** because esx 2.0 for me is shit. nothing works tho and nobody understands what resources do you need now and which not, also I'm not understanding the new way how it works and which resources are integrated... 

**I edited this for ESX 1.2**

**Comment by JulienONN65** [comment]
I invite you to look my pull request : https://github.com/Korioz/krz_personalmenu/pull/59

**Pull request closed without merging**
